/* Integrate with MCP server
   MCP server is also an agent

   Installation of Playwright MCP
   goto Terminal -> Playwright MCP  -> Install it 
   (or)
   goto Terminal -> search for Playwright MCP on browser -> click on "https://github.com/microsoft/playwright-mcp"
   --> goto "Standard config works in most of the tools:" and copy the code (or) click on VS code --> 
   It will directly goto visual studio and asksto install

Playwrite MCP: It acts as an intermediatory between AI and browsers,databases,test execution as it cannot
                directly communicate with browsers,databases,tests

How to use playwright Agent to generate and execute testcases:

what is AI: Artificial Intelligence means something that is developed artificially is known as Artificial intelligence
            AI is a software which interprets your inputs and predicts the answer which means it evaluates
            Testing(means actual+expected) and evaluation means giving clear picture what u want in one sentence
            Asking question is known as prompt Engineering 

what is Agent:  Agent is a software that performs tasks autonomously
                Agent is not an AI but it is part of AI systems which makes certains tasks in betterway
                Agent is expert in certain fields not everything that is called as Agent
                eg: LIC insurance , Lic will not come to us but agent will come to us that is Agent
                    If u go and ask LIC agent about "Max life insurance" he will not know about it so 
                    it is applicable for only one agent


what is MCP(model context protocol) server: MCP is just a communication protocol
            It also takes the prompt and send it to AI model and get the response from AI model
                            first generated by enthropic organization which has developed openAI as well
                            MCP is not an AI but protocol used to communicate with Ai which genrates something

what is playwright Agent: which helps us to generate and execute the testcase using AI model
            Playwright Agents are:
            1. Planner - will generate you the test plan
            2. Generator - generator will generate the testcases
            3. Healer - It will expolre the application,if any error comes, it will fix it across test suite
Install Playwright Agents:
goto Terminal in VS code -> npx playwright init-agents --loop=vscode


what is Prompt Engineering:
        As a prompt engineer first give them a role, generate me automation code using ts/js  for certain examples...etc
How to create effective prompts to get the desired output from AI Model

what is Token: Giving prompt is also a token 
               Every four character which u write considers as 1 token 
               eg: 1Million token may cost $5 where u use AI LLMs
why it is important or why it costs that much:
1. just say : "Generate a testcase for login page" - so you have taken 7 tokens over here
2. one window will have 125000 tokens after that it will ask to open new chat window

*******imp******
Prompt engineering has 3C's to follow which is context,clarity and constrainsts("give me in such a way that i can export" is known as constraints) 
and we need to follow this, instead of using 2000 tokens we can use 700-800 tokens
*******imp******



consider if u give the to copilot as "execute all the testcases and fix the errors if it occurs" and 
it says due to tool limitation cant run the tests  then 
select particular Agent(like planner,generator,healer) ->check for - playwright-test/test_run(if it is present leave as it is)
 ->click on configuration tools ->select built in,playwrite,playwrite-test


 Prompts:
 select agent:

 As a QA Engineer, you are responsible for ensuring the quality of software applications through testing. 
 You will be using Playwright Agents to generate and execute test cases for a web application. 
 Your task is to create effective prompts to get the desired output from the AI model.

 As a QA Engineer, generate me the test automation using playwright and typescript by following the POM
 framework for the below steps.
 1. open "https://rahulshettyacademy.com/client/#/auth/login", 
Enter in Email field as Naveen@gmail.com and enter in Password field as Reddy@36
 2. click on login button
 3. Add product "iphone 13 pro" into the cart
 4. open the cart page
 5. click on checkout
 6. fill random data and place the order
 7. Verify message "Thankyou for the order."

 -->It will create pages folder and under tests->example.spec.ts we will have the code
 Here we will say to AI do this this by giving propmts but it will not validate the things 
 so Playwright MCP comes into picture

 Playwright test planner:
 As a QA Lead, explore the below application and generate a test plan which should have all positive,negative 
 and edge cases scenarios in a detailed manner
 "https://rahulshettyacademy.com/client/#/dashboard/dash"

 Playwright test-generator:
Depending on the test plan generate me the test cases using playwright and typescript by following the 
POM framework and hooks. Add all the page classes inside the pages folder and incase if any data is needed take it from
a file.

As a QA Lead, generate the test case following POM framework using playwright and typescript by referring the testplan
document 

playwright-test healer:
Execute the testcase in headless mode and fix it if their is any failure.

Execute all the testcases in parallel with workers=5 and fix the issues if any failure occurs.




*/